#!/bin/bash
source /etc/os-release
FILE=/boot/vmlinuz-linux
#
echo	------==Script creado por GerardoHD==------
echo  -=Descargando Scripts=-
#
cd /usr/local/bin
echo Intentando identificar el gestor de paquetes de la distribución instalada
sleep 2s 
#
if [ `which pacman` ]; then
	  echo Descargando scripts adecuados para $NAME
	  sleep 3s
	  #
	  sudo rm -rf AUR-Arch
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Arch/AUR-Arch
	  sudo chmod +x AUR-Arch
	  sudo rm -rf AUR-Crostini
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Arch/AUR-Crostini
	  sudo chmod +x AUR-Crostini
	  sudo rm -rf Setup-Arch
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Arch/Setup-Arch
	  sudo chmod +x Setup-Arch
	  sudo rm -rf Setup-Arch-Crostini
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Arch/Setup-Arch-Crostini
	  sudo chmod +x Setup-Arch-Crostini
	   sudo rm -rf Setup-Arch-UKI
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Arch/Setup-Arch-UKI
	  sudo chmod +x Setup-Arch-UKI
	  #
elif [ `which apt` ]; then
	  echo Descargando scripts adecuados para $NAME
	  sudo rm -rf Setup-Debian
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Debian/Setup-Debian
	  sudo chmod +x Setup-Debian
	  sudo rm -rf Setup-Debian-Crostini
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Debian/Setup-Debian-Crostini
	  sudo chmod +x Setup-Debian-Crostini
	  sudo rm -rf Setup-Debian-Repos
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Debian/Setup-Debian-Repos
	  sudo chmod +x Setup-Debian-Repos
	  #
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Debian/sources-testing.list -O /etc/apt/sources-testing.list.bak
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Debian/sources-unstable-experimental.list -O /etc/apt/sources-unstable-experimental.list.bak
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Debian/sources-unstable.list -O /etc/apt/sources-unstable.list.bak
	  #
	  #sudo rm -rf Setup-Ubuntu
	  #sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Debian/Ubuntu/Setup-Ubuntu
	  #sudo chmod +x Setup-Ubuntu
	  #sudo rm -rf Setup-Ubuntu-WSL
	  #sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Debian/Ubuntu/Setup-Ubuntu-WSL
	  #sudo chmod +x Setup-Ubuntu-WSL
	  #
elif [ `which dnf` ]; then
	  echo Descargando scripts adecuados para $NAME $VERSION
	  sleep 3s
	  sudo rm -rf Setup-Fedora
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Fedora/Setup-Fedora
	  sudo chmod +x Setup-Fedora
	  #
fi
	  echo Descargando scripts generales
	  sudo mkdir -p /etc/polkit-1/rules.d/
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/10-rules.rules -O /etc/polkit-1/rules.d/10-rules.rules
	  #sudo rm -rf CrOS-Mount-Partitions
	  #sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/CrOS-Mount-Partitions
	  #sudo chmod +x CrOS-Mount-Partitions
	  sudo rm -rf Setup-Flatpaks
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/Setup-Flatpaks
	  sudo chmod +x Setup-Flatpaks
	  #sudo rm -rf Setup-GNOME-Fonts
	  #sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/Setup-GNOME-Fonts
	  #sudo chmod +x Setup-GNOME-Fonts
	  #sudo rm -rf Setup-GRUB-Default
	  #sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/Setup-GRUB-Default
	  #sudo chmod +x Setup-GRUB-Default
	  sudo rm -rf Setup-Tweaks
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/Setup-Tweaks
	  sudo chmod +x Setup-Tweaks
	  sudo rm -rf Update-Distros
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/Update-Distros
	  sudo chmod +x Update-Distros
	  #
	  sudo rm -rf Scripts-Setup
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/Scripts-Setup
	  sudo chmod +x Scripts-Setup
	  #
	  sudo rm -rf screenfetch-dev
	  sudo wget -c https://raw.githubusercontent.com/KittyKatt/screenFetch/master/screenfetch-dev -O screenfetch-dev
	  sudo chmod +x screenfetch-dev
#
cd ~/
sleep 1s
screenfetch-dev
echo Se aconseja revisar los scripts ubicados en /usr/local/bin/
ls /usr/local/bin/
echo Ejecuta el script elegido
#
