#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
#
echo -=Actualizando software de $NAME=-
#
sudo pacman -Syu --noconfirm
#
cd ~/AUR/
git clone https://aur.archlinux.org/cros-container-guest-tools-git.git
#git clone https://aur.archlinux.org/menulibre.git
cd cros-container-guest-tools-git && makepkg -si --noconfirm
#cd ../menulibre/ && makepkg -si --noconfirm
cd .. && rm -rf cros-container-guest-tools-git #menulibre
#
echo Limpiando archivos antiguos
#rm -rf ~/.config/pulse
cp -r /etc/skel/.config/pulse ~/.config/pulse
#
