#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD
echo Este script solo soporta los siguientes gestores de paquetes: apt, dnf y pacman
echo Ejecutando comandos adecuados para: $NAME
echo Se distribuye con la esperanza de que sea útil, pero sin ninguna garantía
sleep 1s
if [ `which pacman` ]; then
checkupdates
sleep 3s
fi
#
cmd=(dialog --separate-output --checklist "Elige las acciones a realizar" 22 76 16)
options=(1 "Reparar bloqueo de base de datos" off
	 2 "Actualizar" on
	 3 "Limpiar cache de paquetes" off
	 4 "Actualizar y reiniciar" off
	 5 "Actualizar y apagar" off)
choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear
for choice in $choices
do
    case $choice in
	1) #Reparador de bloqueos de base de datos
	if [ `which pacman` ]; then
	  echo  -=Reparando pacman db.lck-
	    sudo rm -f /var/lib/pacman/db.lck
	    if [ "$(id -u)" -eq 0 ] ; then
	    echo " ADVERTENCIA: makepkg no funciona correctamente en una sesion root "
	    echo " Solo se actualizaran paquetes desde los repositorios oficiales"
	    echo " Para actualizar paquetes de AUR, ejecute este script desde su usuario. "
	    pacman -Syu --noconfirm
	    else
	    #echo Remontando /tmp con tamaño de 4 GB
	    #sudo mount -o remount,size=4G,noatime /tmp
	    AUR-Updater
	    flatpak update
	    fi
	  #
	elif [ `which apt` ]; then
	  echo  -=Reparando var=-
	  sudo fuser -vki  /var/lib/dpkg/lock
	  sudo rm -f /var/lib/dpkg/lock
	  sudo dpkg --configure -a
	  sudo apt autoremove
	  sudo apt update --fix-missing
	  flatpak update
	  #
	elif [ `which dnf` ]; then
	  echo No hay comandos disponibles por el momento, falta investigacion
	  #sudo rm /var/lib/dnf/history
	  #
	fi
	;;
	2) #Actualizador de sistema operativo
	if [ `which pacman` ]; then
	  echo  -=Actualizando $NAME=-
	  #echo Remontando /tmp con tamaño de 4 GB
	  #sudo mount -o remount,size=4G,noatime /tmp
	    if [ "$(id -u)" -eq 0 ] ; then
	    echo " ADVERTENCIA: makepkg no funciona correctamente en una sesion root "
	    echo " Solo se actualizaran paquetes desde los repositorios oficiales"
	    echo " Para actualizar paquetes de AUR, ejecute este script desde su usuario. "
	    sudo pacman -Syu --noconfirm
	    else
	    AUR-Updater
	    flatpak update
	    fi
	elif [ `which apt` ]; then
	  echo  -=Actualizando $NAME $VERSION=-
	  sudo apt update
	  sudo apt upgrade -y
	  sudo apt full-upgrade
	  flatpak update
	  #
	elif [ `which dnf` ]; then
	  echo  -=Actualizando $NAME $VERSION=-
	  sudo dnf upgrade --refresh
	  flatpak update
	  #
	fi
	;;
	3) #Limpiador de cache de gestor de paquetes
	if [ `which pacman` ]; then
	  echo  -=Limpiando cache de pacman=-
	  sleep 1s
	  sudo pacman -Scc
	  yay -Scc
	  flatpak uninstall --unused
	  #
	elif [ `which apt` ]; then
	  echo  -=Limpiando cache de apt=-
	  sleep 1s
	  sudo apt clean
	  sudo apt autoclean
	  sudo apt autoremove
	  flatpak uninstall --unused
	  #
	elif [ `which dnf` ]; then
	  echo  -=Limpiando cache de dnf=-
	  sudo dnf list extras
	  sudo dnf autoremove
	  sudo dnf clean all
	  sudo rpm --rebuilddb
	  sudo rm -rf /var/tmp/flatpak-cache*
	  sudo rm -rf /var/cache/abrt-di/*
	  rm -rf $HOME/.cache/debuginfod_client/*
          abrt-cli rm /var/spool/abrt/*
	  flatpak uninstall --unused
	  #
	fi
	;;
	4) #Actualizador de sistema operativo
	if [ `which pacman` ]; then
	    echo  -=Actualizando $NAME y reiniciando el sistema=-
	    #echo Remontando /tmp con tamaño de 4 GB
	    #sudo mount -o remount,size=4G,noatime /tmp
	    if [ "$(id -u)" -eq 0 ] ; then
	    echo " ADVERTENCIA: makepkg no funciona correctamente en una sesion root "
	    echo " Solo se actualizaran paquetes desde los repositorios oficiales"
	    echo " Para actualizar paquetes de AUR, ejecute este script desde su usuario. "
	    pacman -Syu --noconfirm
	    reboot
	    else
	    AUR-Updater
	    flatpak update
	    sudo reboot
	    fi
	  #
	elif [ `which apt` ]; then
	  echo  -=Actualizando $NAME $VERSION y reiniciando el sistema=-
	  sudo apt update
	  sudo apt upgrade -y
	  sudo apt full-upgrade
	  flatpak update
	  sudo reboot
	  #
	elif [ `which dnf` ]; then
	  echo  -=Actualizando $NAME $VERSION y reiniciando el sistema=-
	  sudo dnf upgrade --refresh
	  flatpak update
	  sudo reboot
	  #
	fi
	;;
	5) #Actualizador de sistema operativo
	if [ `which pacman` ]; then
	  echo  -=Actualizando $NAME y apagando el sistema=-
	    #echo Remontando /tmp con tamaño de 4 GB
	    #sudo mount -o remount,size=4G,noatime /tmp
	    if [ "$(id -u)" -eq 0 ] ; then
	    echo " ADVERTENCIA: makepkg no funciona correctamente en una sesion root "
	    echo " Solo se actualizaran paquetes desde los repositorios oficiales"
	    echo " Para actualizar paquetes de AUR, ejecute este script desde su usuario. "
	    pacman -Syu --noconfirm
	    poweroff
	    else
	    AUR-Updater
	    flatpak update
	    sudo poweroff
	    fi
	  #
	elif [ `which apt` ]; then
	  echo  -=Actualizando $NAME $VERSION y apagando el sistema=-
	  sudo apt update
	  sudo apt upgrade -y
	  sudo apt full-upgrade
	  flatpak update
	  sudo poweroff
	  #
	elif [ `which dnf` ]; then
	  echo  -=Actualizando $NAME $VERSION y apagando el sistema=-
	  sudo dnf upgrade --refresh
	  flatpak update
	  sudo poweroff
	  #
	fi
	;;
    esac
done
#
screenfetch-dev
