#!/bin/bash
echo	------==Script Creado por GerardoHD==------
#
echo  -=Configurar tipografias en GNOME=-
PS3='Elige la familia tipografica a usar en GNOME Shell: '
options=("Cantarell" "Fira Sans" "IBM Plex" "Noto Sans" "Roboto" "Ubuntu" "Salir")
select opt in "${options[@]}"
do
    case $opt in
    	"Cantarell")
	  echo Reconfigurando Cantarell como tipografia en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Cantarell 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Cantarell 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Noto Sans Mono Regular 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Cantarell Bold 11'
	  gsettings set org.gnome.totem subtitle-font 'Noto Sans Regular 12'
	  break
	  ;;
	"Fira Sans")
	  echo Configurando Fira Sans como tipografia en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Fira Sans 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Fira Sans Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Fira Mono 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Fira Sans Semibold 11'
	  gsettings set org.gnome.totem subtitle-font 'Fira Sans 12'
	  break
	  ;;
	"IBM Plex")
	  echo Configurando IBM Plex como tipografia en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'IBM Plex Sans Regular 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'IBM Plex Sans Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'IBM Plex Mono Medium 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'IBM Plex Sans Semibold 11'
	  gsettings set org.gnome.totem subtitle-font 'IBM Plex Sans weight=450 12'
	  break
	  ;;
	"Noto Sans")
	  echo Configurando Noto Sans como tipografia en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Noto Sans Regular Medium 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Noto Sans Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Noto Sans Mono Regular 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Noto Sans Semibold 11'
	  gsettings set org.gnome.totem subtitle-font 'Noto Sans Regular 12'
	  break
	  ;;
	"Roboto")
	  echo Configurando Roboto como tipografia en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Roboto Regular 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Roboto Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Roboto Mono Regular 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Roboto Bold 11'
	  gsettings set org.gnome.totem subtitle-font 'Roboto Condensed, 12'
	  break
	  ;;
	"Ubuntu")
	  echo Configurando Ubuntu como tipografia en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Ubuntu Regular 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Ubuntu Medium 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Ubuntu Mono Regular 14'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Ubuntu Bold 11'
	  gsettings set org.gnome.totem subtitle-font 'Ubuntu Condensed, 12'
	  break
	  ;;
	"Salir")
	  break
	  ;;
 	*) echo invalid option;;
    esac
done
#
