#!/bin/bash
source /etc/os-release
FILE=/boot/vmlinuz-linux
#
echo	------==Script Creado por GerardoHD==------
#
if [ "$(id -u)" -eq 0 ] ; then
echo " Este script usa sudo cuando es necesario. Deteniendo. "
echo " Simplemente ejecute este script desde su usuario. "
exit
fi
#
PS3='Elige la accion a realizar: '
options=("Aplicar modificaciones a gsettings" "Actualizar carpetas de usuario" "Esconder entradas .desktop" "Descargar iconos en .png" "Descargar customizaciones" "Salir")
select opt in "${options[@]}"
do
    case $opt in
	"Aplicar modificaciones a gsettings")
	  echo Reconfigurando Cantarell como tipografia de las aplicaciones
	  gsettings set org.gnome.desktop.interface font-name 'Cantarell 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Cantarell 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Noto Sans Mono Regular 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Cantarell Bold 11'
	  echo Configurando botones de la barra de título
	  gsettings set org.gnome.desktop.wm.preferences button-layout ':close'
	  echo Configurando Tema GTK
	  gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'
	  echo Configurando tap-to-click en GNOME Shell
	  gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
	  echo Configurando el botón de Apagado a interactivo
	  gsettings set org.gnome.settings-daemon.plugins.power power-button-action 'interactive'
	  echo Configurando Alt+Tab para que cambie solo entre aplicaciones de la misma area de trabajo
	  gsettings set org.gnome.shell.app-switcher current-workspace-only true
	  break
	  ;;
	"Actualizar carpetas de usuario")
	  xdg-user-dirs-update
	  break
	  ;;
	"Esconder entradas .desktop")
	  mkdir -p ~/.local/share/applications/
	  #
	  rm ~/.local/share/applications/avahi-discover.desktop
	  cp /usr/share/applications/avahi-discover.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/avahi-discover.desktop
	  #
	  rm ~/.local/share/applications/bvnc.desktop
	  cp /usr/share/applications/bvnc.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/bvnc.desktop
	  #
	  rm ~/.local/share/applications/bssh.desktop
	  cp /usr/share/applications/bssh.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/bssh.desktop
	  #
	  rm ~/.local/share/applications/calibre-ebook-edit.desktop
	  cp /usr/share/applications/calibre-ebook-edit.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/calibre-ebook-edit.desktop
	  #
	  rm ~/.local/share/applications/calibre-ebook-viewer.desktop
	  cp /usr/share/applications/calibre-ebook-viewer.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/calibre-ebook-viewer.desktop
	  #
	  rm ~/.local/share/applications/calibre-lrfviewer.desktop
	  cp /usr/share/applications/calibre-lrfviewer.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/calibre-lrfviewer.desktop
	  #
	  rm ~/.local/share/applications/cmake-gui.desktop
	  cp /usr/share/applications/cmake-gui.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/cmake-gui.desktop
	  #
	  sudo rm ~/.local/share/applications/cups.desktop
	  cp /usr/share/applications/cups.desktop ~/.local/share/applications/cups.desktop
	  echo Para esconder el acceso a la Interfaz Web de CUPS:
	  echo Añadir "NoDisplay=true" a ~/.local/share/applications/cups.desktop
	  sleep 3s
	  sudo vim ~/.local/share/applications/cups.desktop
	  #
	  rm ~/.local/share/applications/display-im6.q16.desktop
	  cp /usr/share/applications/display-im6.q16.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/display-im6.q16.desktop
	  #
	  rm ~/.local/share/applications/lstopo.desktop
	  cp /usr/share/applications/lstopo.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/lstopo.desktop
	  #
	  rm ~/.local/share/applications/nm-connection-editor.desktop
	  cp /usr/share/applications/nm-connection-editor.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/nm-connection-editor.desktop
	  #
	  rm ~/.local/share/applications/org.freedesktop.MalcontentControl.desktop
	  cp /usr/share/applications/org.freedesktop.MalcontentControl.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/org.freedesktop.MalcontentControl.desktop
	  #
	  rm ~/.local/share/applications/mpv.desktop
	  cp /usr/share/applications/mpv.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/mpv.desktop
	  #
	  rm ~/.local/share/applications/qv4l2.desktop
	  cp /usr/share/applications/qv4l2.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/qv4l2.desktop
	  #
	  rm ~/.local/share/applications/qvidcap.desktop
	  cp /usr/share/applications/qvidcap.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/qvidcap.desktop
	  #
	  rm ~/.local/share/applications/system-config-printer.desktop
	  cp /usr/share/applications/system-config-printer.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/system-config-printer.desktop
	  #
	  rm ~/.local/share/applications/vim.desktop
	  cp /usr/share/applications/vim.desktop ~/.local/share/applications/
	  echo NoDisplay=true >> ~/.local/share/applications/vim.desktop
	  #
	  break
	  ;;
	"Descargar iconos en .png")
	  if [ ! -e "$FILE" ]; then
	  echo Actualizando iconos en .png para aplicaciones de GNOME
	  cd /usr/share/icons/hicolor/128x128/apps
	  #
	  sudo rm org.gnome.ArchiveManager.png
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/org.gnome.ArchiveManager.png
	  sudo rm org.gnome.baobab.png
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/org.gnome.baobab.png
	  sudo rm  org.gnome.Evince.png
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/org.gnome.Evince.png
	  sudo rm org.gnome.font-viewer.png
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/org.gnome.font-viewer.png
	  sudo rm org.gnome.gedit.png
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/org.gnome.gedit.png
	  sudo rm org.gnome.Lollypop.png
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/org.gnome.Lollypop.png
	  sudo rm org.gnome.Nautilus.png
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/org.gnome.Nautilus.png
	  sudo rm org.gnome.Software.png
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/org.gnome.Software.png
	  sudo rm org.gnome.Yelp.png
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/org.gnome.Yelp.png
	  #
	  cd ~
	  else
	  echo Esta opcion solo es útil en Crostini, saliendo
	  fi
	  break
	  ;;
	"Descargar customizaciones")
      #
	  echo Creando carpeta Git
	  mkdir Git
      cd Git
	  #
	  #adw-gtk3
      wget -c  https://github.com/lassekongo83/adw-gtk3/releases/latest/download/adw-gtk3v5.3.tar.xz
      tar -xf adw-gtk3v5.3.tar.xz
      sudo cp -rf adw-gtk3 /usr/share/themes/
      sudo cp -rf adw-gtk3-dark /usr/share/themes/
      sudo rm -rf adw-gtk3*
      #
      #Firefox GNOME Theme
      git clone https://github.com/rafaelmardojai/firefox-gnome-theme.git
      cd firefox-gnome-theme
      git pull
      ./scripts/install.sh
      cd ..
      #
      #adw-gtk2
      git clone https://github.com/molotov-dmitry/adw-gtk2.git
      cd adw-gtk2
      git pull
      sudo cp -rf adw-gtk3 /usr/share/themes/
      sudo cp -rf adw-gtk3-dark /usr/share/themes/
      cd ..
      #
      #adw-xfwm4
      git clone https://github.com/FabianOvrWrt/adw-xfwm4.git
      cd adw-xfwm4
      git pull
      sudo cp -rf themes/* /usr/share/themes/
      cd ..
      #
      #KvLibadwaita GabePoel --Original
      #git clone https://github.com/GabePoel/KvLibadwaita.git
      #cd KvLibadwaita
      #sudo ./install.sh
      #cd ..
      #
      #KvLibadwaita BigLinux --fork
      git clone https://github.com/biglinux/KvLibadwaita.git
      cd KvLibadwaita
      git pull
      sudo ./install.sh
      cd ..
      #
      #Adwaita-for-Steam
      git clone https://github.com/tkashkin/Adwaita-for-Steam
      cd Adwaita-for-Steam
      git pull
      ./install.py
      cd ..
      #
	  #MoreWaita Icons
	  #git clone https://github.com/somepaulo/MoreWaita.git
	  #cd Morewaita
	  #git pull
	  #./install.sh
	  #cd ..
	  #
	  echo Descargando iconos para Xfce weather plugin
	  git clone https://github.com/kevin-hanselman/xfce4-weather-mono-icons.git
	  cd xfce4-weather-mono-icons/
	  #
	  rm -rf /usr/share/xfce4/weather/icons/WSky*
	  sudo cp -a WSky /usr/share/xfce4/weather/icons
	  sudo cp -a WSky-Light /usr/share/xfce4/weather/icons
	  cd ..
	  #
	  cd ~
	  #
	  sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/icons/
	  unzip "Clima-20190419213247.zip" -d Clima
	  #
	  rm -rf /usr/share/xfce4/weather/icons/Clima*
	  sudo mv Clima/20190419/Clima /usr/share/xfce4/weather/icons
	  sudo mv Clima/20190419/Clima-B /usr/share/xfce4/weather/icons
	  sudo mv Clima/20190419/Clima-W /usr/share/xfce4/weather/icons
	  sudo rm -rf Clima*
	  #
      #Blender Icons para GIMP
      #sudo mkdir -p /usr/share/gimp/2.0/icons/
      #wget -c https://github.com/Uzugijin/GIMP-IconThemes/releases/download/v1.0.2/BlenderIcons-1-0-2.zip
      #unzip BlenderIcons-1-0-2.zip
      #sudo mv BlenderIcons /usr/share/gimp/2.0/icons/
      #
      #wget -c https://github.com/Uzugijin/GIMP-IconThemes/releases/download/v1.0.2/BlenderSymbolic-1-0-2.zip
      #unzip BlenderSymbolic-1-0-2.zip
      #sudo mv BlenderSymbolic /usr/share/gimp/2.0/icons/
      #rm -rf Blender*
      #
      echo Instalando Bibata Cursors
      wget -c  https://github.com/ful1e5/Bibata_Cursor/releases/latest/download/Bibata-Modern-Classic.tar.xz
      wget -c  https://github.com/ful1e5/Bibata_Cursor/releases/latest/download/Bibata-Modern-Ice.tar.xz
	  #
      tar -xvf Bibata-Modern-Classic.tar.xz
      tar -xvf Bibata-Modern-Ice.tar.xz
      #
	  sudo rm -rf /usr/share/icons/Bibata*
	  sudo mv Bibata-Modern-Classic /usr/share/icons/
      sudo mv Bibata-Modern-Ice /usr/share/icons/
      rm -rf Bibata*
      #
      cd ~/
      #
      echo Instalando Papirus Icon Theme
      wget -qO- https://git.io/papirus-icon-theme-install | sh
	  #
	  echo Descargando Fira Fonts
	  wget -c https://github.com/mozilla/Fira/archive/refs/tags/4.106.zip -O "Fira_Sans_4.106_&_Mono_3.206.zip"
	  wget -c https://github.com/mozilla/Fira/archive/refs/tags/4.202.zip -O "Fira_Sans_Condensed_4.202.zip"
	  wget -c https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip -O "Fira_Code_v6.2.zip"
	  #
	  unzip "Fira_Sans_4.106_&_Mono_3.206.zip" -d Fira_Sans
	  unzip "Fira_Sans_Condensed_4.202.zip" -d Fira_Sans_Condensed
	  unzip "Fira_Code_v6.2.zip" -d Fira_Code
	  #
	  sudo rm -rf /usr/share/fonts/truetype/Fira*
	  sudo mv Fira_Sans/Fira-4.106/ttf /usr/share/fonts/truetype/Fira_Sans
	  sudo mv Fira_Sans_Condensed/Fira-4.202/ttf/ /usr/share/fonts/truetype/Fira_Sans_Condensed
	  sudo mv Fira_Code/ttf /usr/share/fonts/truetype/Fira_Code
	  rm -rf Fira*
	  #
      break
      ;;
	"Salir")
	  break
	  ;;
	*) echo invalid option;;
	esac
done
#