#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD
echo Script creado para configurar un sistema $NAME
echo Se distribuye con la esperanza de que sea util, pero sin ninguna garantia
sleep 3s
#
sudo addgroup optical
sudo addgroup power
sudo addgroup storage
sudo addgroup wheel
sudo nano /etc/sudoers
#
sudo apt install bash-completion dialog -y #preinstalado en C330
sudo apt install apt-listbugs apt-listchanges -y
sudo apt install cmatrix cmatrix-xfont fastfetch -y
#
echo Cambiando a repositorios testing
#sudo mv /etc/apt/sources.list /etc/apt/sources.list-sta.bak
#echo >> sources.list
#sudo sed -i '$ a\deb http://deb.debian.org/debian/ testing main contrib non-free-firmware' sources.list
#sudo sed -i '$ a\deb-src http://deb.debian.org/debian/ testing main contrib non-free-firmware' sources.list
#sudo sed -i '$ a\deb https://deb.debian.org/debian testing-updates main contrib non-free-firmware' sources.list
#sudo sed -i '$ a\deb-src https://deb.debian.org/debian testing-updates main contrib non-free-firmware' sources.list
#sudo sed -i '$ a\deb https://deb.debian.org/debian-security/ testing-security main' sources.list
#sudo sed -i '$ a\deb-src https://deb.debian.org/debian-security/ testing-security main' sources.list
#sudo mv sources.list /etc/apt/sources.list
sudo apt update --allow-releaseinfo-change
sudo apt dist-upgrade -y
sudo apt autoremove -y
sudo apt clean
sudo apt autoclean
#
sudo apt install curl gpg wget git apt-transport-https -y #en C330 solo se instala apt-transport-https
sudo apt install cmake -y
sudo apt install btrfs-progs f2fs-tools reiserfsprogs xfsprogs ntfs-3g jfsutils xfsdump nilfs-tools -y #en c330 excluir btrfs ntfs
sudo apt install lzip minizip unace arj ncompress p7zip unrar-free lrzip zip squashfs-tools lzop rzip -y #en c330 excluir zip
sudo apt install pv tar cgpt vboot-utils -y #en c330 solo pv
sudo apt install apt-config-icons-hidpi -y
sudo apt install sbsigntool -y
sudo apt install adb fastboot -y
sudo apt install blueman gvfs* -y
#
#Fuentes
sudo apt install fonts-cantarell fonts-liberation fonts-linuxlibertine -y #en c330 solo se instala libertine
sudo apt install fonts-crosextra* -y
sudo apt install ttf-mscorefonts-installer cabextract fonts-ibm-plex -y
#mkdir .fonts
#wget -qO- http://plasmasturm.org/code/vistafonts-installer/vistafonts-installer | bash
#rm PowerPointViewer.exe
#
echo Descargando reglas de polkit para realizar actividades de administracion sin pedir autenticacion
sudo mkdir -p /etc/polkit-1/rules.d/
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/10-rules.rules -O /etc/polkit-1/rules.d/10-rules.rules
#
#Soporte Flatpak
sudo apt install flatpak -y
#sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
#sudo flatpak update --appstream
#
sudo apt install gtk2-engines -y
sudo apt install gtk2-engines-aurora -y
sudo apt install gtk2-engines-murrine -y
sudo apt install gtk2-engines-oxygen -y
#
#echo Instalando Firefox GNOME Theme
#mkdir Git
#cd Git
#git clone https://github.com/rafaelmardojai/firefox-gnome-theme.git
#cd firefox-gnome-theme/scripts/
#./install.sh
#cd ~/
#
echo Instalando Papirus Icon Theme
#wget -qO- https://git.io/papirus-icon-theme-install | sh
#
echo  -=Software Grafico=-
	  cmd=(dialog --separate-output --checklist "Elige el software a instalar: " 22 76 16)
	  options=(1 "Paquetes desde APT" on
	           2 "Programas para C2" off
	           3 "Visual Studio Code" on
	           4 "Flatpaks" on
	           5 "Instalar GNOME" off
	           6 "Instalar KDE" off)
	  choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
	  clear
	  for choice in $choices
	  do
	      case $choice in
	  	1)
          #sudo apt install light-locker lightdm-gtk-greeter lightdm-gtk-greeter-settings gnome-screensaver lightdm-settings #en c330 preinstalado light-locker
          #sudo sed -i 's/greeter-session=slick-greeter/greeter-session=lightdm-gtk-greeter/g' /etc/lightdm/lightdm.conf
          #sudo sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-gtk-greeter/g' /etc/lightdm/lightdm.conf
          sudo apt install mugshot galculator -y
          sudo apt install chromium chromium-l10n chromium-driver -y
          sudo apt install hunspell-es hyphen-es libreoffice-gtk4 libreoffice-help-es libreoffice-l10n-es -y
          sudo apt install libreoffice-style-breeze libreoffice-style-sifr libreoffice-style-sukapura -y
          sudo apt install mythes-es -y
          sudo apt install libreoffice-gtk3 libreoffice-voikko -y
	  	  sudo apt install libreoffice-l10n-es -y
	  	  sudo apt install libreoffice-java-common -y
	  	  sudo apt install libreoffice-calc -y
	  	  sudo apt install libreoffice-impress -y
	  	  sudo apt install libreoffice-writer -y
          sudo apt install gimp gimp-data-extras -y
          sudo apt install gparted baobab -y
          sudo apt install gdisk -y
          sudo apt install openssh-server sshfs -y
		  sudo apt install kdeconnect -y
          sudo apt purge --remove gnome-system-monitor -y
	  	  ;;
	  	2)
	  	  sudo apt install ntpsec -y
          sudo apt install atril -y
          sudo apt install gnome-system-tools -y
          sudo apt purge --remove goldendict -y
	  	  ;;
	  	3)
	  	  sudo apt-get install wget gpg
	  	  #wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
		  #sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
		  #sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
		  #rm -f packages.microsoft.gpg
		  sudo apt update
		  sudo apt install code -y
	  	  ;;
	  	4)
	  	  #Flatpaks-Setup
          ./FS
	  	  ;;
	  	5)
	  	  sudo apt install task-gnome-desktop -y
          sudo apt install gnome-software gnome-software-plugin-flatpak -y
          sudo apt install gedit-plugins -y
          sudo apt install geary menulibre -y
		  sudo apt purge --remove kdeconnect -y
	  	  ;;
		6)
	  	  sudo apt install task-kde-desktop -y
          sudo dpkg-reconfigure sddm -y
          sudo apt install kaccounts-integration kaccounts-providers -y
          sudo apt install kde-config-flatpak plasma-discover-backend-flatpak -y
          sudo apt install kde-config-plymouth -y
          sudo apt install filelight -y
          sudo apt install dolphin-plugins -y
          sudo apt install kde-config-gtk-style-preview -y
          sudo apt install kwin-addons -y
          sudo apt install okular-extra-backends -y
          sudo apt install quota -y
          #
          sudo apt --purge remove *xfce* -y
          sudo apt --purge remove gnome-system-monitor -y
          sudo apt --purge remove mousepad -y
          sudo apt --purge remove quodlibet -y
          sudo apt --purge remove atril -y
          sudo apt --purge remove blueman -y
	  	  ;;
	     esac
	  done
	  #
#
echo Copiando archivos
sudo cp -rf Debian3/Debian/FS/* /
#
echo  -=Actualizando y limpiando $NAME $VERSION=-
sudo apt update
sudo apt upgrade -y
sudo apt clean
sudo apt autoclean
sudo apt autoremove -y
df -h
sleep 3s
fastfetch
#