#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD
echo Script creado para configurar un sistema $NAME
echo Se distribuye con la esperanza de que sea util, pero sin ninguna garantia
sleep 3s
#
sudo addgroup optical
sudo addgroup power
sudo addgroup storage
sudo addgroup wheel
sudo usermod -aG optical,power,storage,wheel gerardohd
sudo nano /etc/sudoers
#
sudo apt install bash-completion dialog -y #preinstalado en C330
sudo apt install apt-listbugs apt-listchanges apt-utils apt-transport-https -y
sudo apt install cmatrix cmatrix-xfont fastfetch -y
#
echo Cambiando a repositorios testing
sudo mv /etc/apt/sources.list /etc/apt/sources.list-sta.bak
echo >> sources.list
sudo sed -i '$ a\deb http://deb.debian.org/debian/ testing main contrib non-free-firmware' sources.list
sudo sed -i '$ a\deb-src http://deb.debian.org/debian/ testing main contrib non-free-firmware' sources.list
sudo sed -i '$ a\deb https://deb.debian.org/debian testing-updates main contrib non-free-firmware' sources.list
sudo sed -i '$ a\deb-src https://deb.debian.org/debian testing-updates main contrib non-free-firmware' sources.list
sudo sed -i '$ a\deb https://deb.debian.org/debian-security/ testing-security main' sources.list
sudo sed -i '$ a\deb-src https://deb.debian.org/debian-security/ testing-security main' sources.list
sudo mv sources.list /etc/apt/sources.list
sudo apt update --allow-releaseinfo-change
sudo apt dist-upgrade -y
sudo apt autoremove -y
sudo apt clean
sudo apt autoclean
#
sudo apt install curl gpg wget git -y
sudo apt install cmake -y
sudo apt install btrfs-progs f2fs-tools reiserfsprogs xfsprogs ntfs-3g jfsutils xfsdump nilfs-tools -y #en c330 excluir btrfs ntfs
#sudo apt install gvfs* fuse fuse-overlayfs fuse-zip fuse2fs exfat-fuse fusefat fuseiso* -y
sudo apt install lzip minizip unace arj ncompress p7zip-full unrar-free lrzip zip squashfs-tools lzop rzip -y #en c330 excluir zip
sudo apt install pv tar cgpt vboot-utils -y #en c330 solo pv
sudo apt install apt-config-icons-hidpi -y
sudo apt install sbsigntool -y
sudo apt install adb fastboot -y
sudo apt install openssh-server sshfs -y
#
#Fuentes
sudo apt install fonts-cantarell fonts-liberation fonts-linuxlibertine -y #en c330 solo se instala libertine
sudo apt install fonts-crosextra* -y
sudo apt install ttf-mscorefonts-installer cabextract fonts-ibm-plex -y
mkdir .fonts
wget -qO- http://plasmasturm.org/code/vistafonts-installer/vistafonts-installer | bash
rm PowerPointViewer.exe
#
echo Descargando reglas de polkit para realizar actividades de administracion sin pedir autenticacion
sudo mkdir -p /etc/polkit-1/rules.d/
sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/10-rules.rules -O /etc/polkit-1/rules.d/10-rules.rules
#
#Soporte Flatpak
sudo apt install flatpak xdg-desktop-portal-xapp -y
sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
sudo flatpak update --appstream
#
sudo apt install gtk2-engines -y
sudo apt install gtk2-engines-aurora -y
sudo apt install gtk2-engines-murrine -y
sudo apt install gtk2-engines-oxygen -y
sudo apt install qt5-style-kvantum*
#
echo Instalando Temas Adwaita
#
#adw-gtk3
wget -c  https://github.com/lassekongo83/adw-gtk3/releases/latest/download/adw-gtk3v5.3.tar.xz
tar -xf adw-gtk3v5.3.tar.xz
sudo mv -rf adw-gtk3 /usr/share/themes/
sudo mv -rf adw-gtk3-dark /usr/share/themes/
rm -rf adw-gtk3*
#
#Firefox GNOME Theme
mkdir Git
cd Git
git clone https://github.com/rafaelmardojai/firefox-gnome-theme.git
./firefox-gnome-theme/scripts/install.sh
#
#adw-gtk2
git clone https://github.com/molotov-dmitry/adw-gtk2.git
sudo cp -rf adw-gtk2/adw-gtk3 /usr/share/themes/
sudo cp -rf adw-gtk2/adw-gtk3-dark/ /usr/share/themes/
#
#adw-xfwm4
git clone https://github.com/FabianOvrWrt/adw-xfwm4.git
sudo cp -rf adw-xfwm4/themes/* /usr/share/themes/
#
#KvLibadwaita GabePoel --Original
#git clone https://github.com/GabePoel/KvLibadwaita.git
#cd KvLibadwaita
#sudo ./install.sh
#cd ..
#
#KvLibadwaita BigLinux --fork
git clone https://github.com/biglinux/KvLibadwaita.git
cd KvLibadwaita
sudo ./install.sh
cd ..
#
#Adwaita-for-Steam
#git clone https://github.com/tkashkin/Adwaita-for-Steam
#cd Adwaita-for-Steam
#./install.py
#cd ..
#
cd ~/
#
gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3' && gsettings set org.gnome.desktop.interface color-scheme 'default'
#
#Blender Icons GIMP
wget -c https://github.com/Uzugijin/GIMP-IconThemes/releases/download/v1.0.2/BlenderIcons-1-0-2.zip
unzip BlenderIcons-1-0-2.zip
sudo cp -rf BlenderIcons /usr/share/gimp/2.0/icons/
#
wget -c https://github.com/Uzugijin/GIMP-IconThemes/releases/download/v1.0.2/BlenderSymbolic-1-0-2.zip
unzip BlenderSymbolic-1-0-2.zip
sudo cp -rf BlenderSymbolic /usr/share/gimp/2.0/icons/
rm -rf Blender*
#
echo Instalando Papirus Icon Theme
wget -qO- https://git.io/papirus-icon-theme-install | sh
#
echo Instalando Bibata Cursors
wget -c  https://github.com/ful1e5/Bibata_Cursor/releases/latest/download/Bibata-Modern-Classic.tar.xz
wget -c  https://github.com/ful1e5/Bibata_Cursor/releases/latest/download/Bibata-Modern-Ice.tar.xz
tar -xvf Bibata-Modern-Classic.tar.xz
tar -xvf Bibata-Modern-Ice.tar.xz
sudo mv Bibata-Modern-Classic /usr/share/icons/
sudo mv Bibata-Modern-Ice /usr/share/icons/
rm Bibata*
#
echo  -=Software Grafico=-
	  cmd=(dialog --separate-output --checklist "Elige el software a instalar: " 22 76 16)
	  options=(1 "Software desde APT" on
	           2 "Software para C2" off
	           3 "Visual Studio Code" on
	           4 "Flatpaks" on
	           5 "Instalar GNOME" off
	           6 "Instalar KDE" off)
	  choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
	  clear
	  for choice in $choices
	  do
	      case $choice in
	  	1)
          sudo apt install light-locker lightdm-gtk-greeter lightdm-gtk-greeter-settings gnome-screensaver lightdm-settings #en c330 preinstalado light-locker
          sudo sed -i 's/greeter-session=slick-greeter/greeter-session=lightdm-gtk-greeter/g' /etc/lightdm/lightdm.conf
          sudo sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-gtk-greeter/g' /etc/lightdm/lightdm.conf
          sudo apt install mugshot galculator -y
          sudo apt install chromium chromium-l10n chromium-driver -y
          sudo apt install hunspell-es hyphen-es libreoffice-gtk4 libreoffice-help-es libreoffice-l10n-es -y
          sudo apt install libreoffice-style-breeze libreoffice-style-sifr libreoffice-style-sukapura -y
          sudo apt install mythes-es firefox-esr-l10n-es-mx -y
          sudo apt install libreoffice-gtk3 libreoffice-voikko -y
	  	  sudo apt install libreoffice-l10n-es -y
	  	  sudo apt install libreoffice-java-common -y
	  	  sudo apt install libreoffice-calc -y
	  	  sudo apt install libreoffice-impress -y
	  	  sudo apt install libreoffice-writer -y
          sudo apt install gimp gimp-data-extras inkscape inkscape-open-symbols inkscape-tutorials -y
          sudo apt install gparted -y
		  sudo apt install baobab gnome-2048 gnome-disk-utility gnome-font-viewer gnome-mines gnome-nibbles gnome-sudoku gnome-taquin gnome-tetravex -y
		  sudo apt install gnome-software gnome-software-plugin* -y
          sudo apt install gdisk -y
          sudo apt install sshfsblueman -y
		  sudo apt install kdeconnect -y
		  #
          sudo apt purge --remove gnome-system-monitor -y
	  	  ;;
	  	2)
	  	  sudo apt install ntpsec -y
          sudo apt install atril -y
          sudo apt install gnome-system-tools -y
          sudo apt purge --remove goldendict -y
		  #
		  mkdir ~/AppImage
		  cd ~/AppImage
		  wget -c  https://download.beeper.com/linux/appImage/x64 -O Beeper.appimage
		  chmod +x Beeper.appimage
		  cd ~/
		  #
		  sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=1/g' /etc/default/grub
		  sudo update-grub
	  	  ;;
	  	3)
	  	  sudo apt-get install wget gpg
	  	  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
		  sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
		  sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
		  rm -f packages.microsoft.gpg
		  sudo apt update
		  sudo apt install code -y
	  	  ;;
	  	4)
	  	  Flatpaks-Setup
	  	  ;;
	  	5)
	  	  sudo apt install task-gnome-desktop -y
          sudo apt install gedit-plugins -y
          sudo apt install geary menulibre -y
		  sudo apt purge --remove kdeconnect -y
	  	  ;;
		6)
	  	  sudo apt install task-kde-desktop -y
          sudo dpkg-reconfigure sddm -y
          sudo apt install kaccounts-integration kaccounts-providers -y
          sudo apt install kde-config-flatpak plasma-discover-backend-flatpak -y
          sudo apt install kde-config-plymouth -y
          sudo apt install filelight -y
          sudo apt install dolphin-plugins -y
          sudo apt install kde-config-gtk-style-preview -y
          sudo apt install kwin-addons -y
          sudo apt install okular-extra-backends -y
          sudo apt install quota -y
          #
          sudo apt --purge remove *xfce* -y
          sudo apt --purge remove gnome-system-monitor -y
          sudo apt --purge remove mousepad -y
          sudo apt --purge remove quodlibet -y
          sudo apt --purge remove atril -y
          sudo apt --purge remove blueman -y
	  	  ;;
	     esac
	  done
	  #
#
echo Copiando archivos
7z x Debian-FS.7z
sudo cp -rf Debian-FS/* /
#
echo  -=Actualizando y limpiando $NAME $VERSION=-
sudo apt update
sudo apt upgrade -y
sudo apt clean
sudo apt autoclean
sudo apt autoremove -y
df -h
sleep 3s
fastfetch
#
