#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD
echo Script creado para configurar un sistema $NAME
echo Se distribuye con la esperanza de que sea util, pero sin ninguna garantia
sleep 3s
#
sudo addgroup optical
sudo addgroup power
sudo addgroup storage
sudo addgroup wheel
sudo usermod -aG optical,power,storage,wheel gerardohd
sudo nano /etc/sudoers
#
sudo apt install bash-completion manpages-es dialog -y
sudo apt install apt-listbugs apt-listchanges apt-utils apt-transport-https -y
sudo apt install cmatrix cmatrix-xfont fastfetch -y
#
#Cambiar repositorios de Debian
echo Respaldando sources.list
sudo cp /etc/apt/sources.list /etc/apt/sources-default.list.bak
Setup-Debian-Repos
#
sudo apt install curl gpg wget git -y
sudo apt install cmake -y
sudo apt install btrfs-progs f2fs-tools reiserfsprogs xfsprogs ntfs-3g jfsutils xfsdump nilfs-tools -y
#sudo apt install gvfs* fuse fuse-overlayfs fuse-zip fuse2fs exfat-fuse fusefat fuseiso* -y #desactivado porque hay conflicto de fuse con fuse3
sudo apt install lzip minizip unace arj ncompress p7zip-full unrar-free lrzip zip squashfs-tools lzop rzip -y
sudo apt install pv tar cgpt vboot-utils -y
sudo apt install apt-config-icons-hidpi -y
sudo apt install sbsigntool -y
sudo apt install adb fastboot -y
sudo apt install openssh-server sshfs -y
sudo apt install ffmpegthumbnailer exiv2 -y
#
#Fuentes
sudo apt install fonts-cantarell fonts-liberation fonts-linuxlibertine -y
sudo apt install fonts-crosextra* -y
sudo apt install ttf-mscorefonts-installer cabextract fonts-ibm-plex -y
mkdir .fonts
wget -qO- http://plasmasturm.org/code/vistafonts-installer/vistafonts-installer | bash
rm PowerPointViewer.exe
#
#Soporte Flatpak
sudo apt install flatpak xdg-desktop-portal-xapp -y
sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
sudo flatpak update --appstream
#
#Motores de temas
sudo apt install gtk2-engines -y
sudo apt install gtk2-engines-aurora -y
sudo apt install gtk2-engines-murrine -y
sudo apt install gtk2-engines-oxygen -y
sudo apt install qt5-style-kvantum*
#
Setup-Tweaks
#
echo  -=Software Grafico=-
	  cmd=(dialog --separate-output --checklist "Elige el software a instalar: " 22 76 16)
	  options=(1 "Software desde APT" on
	           2 "Software para C2" off
	           3 "Visual Studio Code" on
	           4 "Instalar Flatpaks" on
	           5 "Instalar GNOME" off
	           6 "Instalar KDE" off)
	  choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
	  clear
	  for choice in $choices
	  do
	      case $choice in
	  	1)
          sudo apt install light-locker lightdm-gtk-greeter lightdm-gtk-greeter-settings gnome-screensaver lightdm-settings #en c330 preinstalado light-locker
          sudo sed -i 's/greeter-session=slick-greeter/greeter-session=lightdm-gtk-greeter/g' /etc/lightdm/lightdm.conf
          sudo sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-gtk-greeter/g' /etc/lightdm/lightdm.conf
          sudo apt install mugshot galculator -y
          sudo apt install chromium chromium-l10n chromium-driver -y
          sudo apt install firefox-esr-l10n-es-mx -y
          sudo apt install libreoffice-gtk3 liblibreofficekitgtk libreoffice-voikko mythes-es -y
		  sudo apt install hunspell-es hyphen-es libreoffice-gtk4 libreoffice-help-es libreoffice-l10n-es -y
          sudo apt install libreoffice-style-breeze libreoffice-style-sifr libreoffice-style-sukapura -y
	  	  sudo apt install libreoffice-l10n-es -y
	  	  sudo apt install libreoffice-java-common -y
	  	  sudo apt install libreoffice-calc -y
	  	  sudo apt install libreoffice-impress -y
	  	  sudo apt install libreoffice-writer -y
          sudo apt install gimp gimp-data-extras inkscape inkscape-open-symbols inkscape-tutorials -y
          sudo apt install gparted -y
		  sudo apt install baobab gnome-2048 gnome-disk-utility gnome-font-viewer gnome-mines gnome-nibbles gnome-sudoku gnome-taquin gnome-tetravex -y
		  sudo apt install gnome-software gnome-software-plugin* -y
          sudo apt install gdisk -y
          sudo apt install sshfs blueman -y
		  sudo apt install kdeconnect -y
		  #
          sudo apt purge --remove gnome-system-monitor -y
	  	  ;;
	  	2)
	  	  sudo apt install ntpsec -y
          sudo apt install atril -y
          sudo apt install gnome-system-tools -y
          sudo apt purge --remove goldendict -y
		  #
		  mkdir ~/AppImage
		  cd ~/AppImage
		  wget -c  https://download.beeper.com/linux/appImage/x64 -O Beeper.appimage
		  chmod +x Beeper.appimage
		  cd ~/
		  #
		  echo Modificando tiempo de espera de GRUB
		  sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=1/g' /etc/default/grub
		  sudo update-grub
	  	  ;;
	  	3)
	  	  sudo apt-get install wget gpg
	  	  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
		  sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
		  sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
		  rm -f packages.microsoft.gpg
		  sudo apt update
		  sudo apt install code -y
	  	  ;;
	  	4)
	  	  Setup-Flatpaks
	  	  ;;
	  	5)
	  	  sudo apt install task-gnome-desktop -y
          sudo apt install gedit-plugins -y
          sudo apt install geary menulibre -y
		  sudo apt purge --remove kdeconnect -y
	  	  ;;
		6)
	  	  sudo apt install task-kde-desktop -y
          sudo dpkg-reconfigure sddm -y
          sudo apt install kaccounts-integration kaccounts-providers -y
          sudo apt install kde-config-flatpak plasma-discover-backend-flatpak -y
          sudo apt install kde-config-plymouth -y
          sudo apt install filelight -y
          sudo apt install dolphin-plugins -y
          sudo apt install kde-config-gtk-style-preview -y
          sudo apt install kwin-addons -y
          sudo apt install okular-extra-backends -y
          sudo apt install quota -y
          #
          sudo apt --purge remove *xfce* -y
          sudo apt --purge remove gnome-system-monitor -y
          sudo apt --purge remove mousepad -y
          sudo apt --purge remove quodlibet -y
          sudo apt --purge remove atril -y
          sudo apt --purge remove blueman -y
	  	  ;;
	     esac
	  done
	  #
#
gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3' && gsettings set org.gnome.desktop.interface color-scheme 'default'
#
echo  -=Actualizando y limpiando $NAME $VERSION=-
sudo apt update
sudo apt upgrade -y
sudo apt clean
sudo apt autoclean
sudo apt autoremove -y
df -h
sleep 3s
fastfetch
#
