#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD
echo Script creado para configurar $NAME $VERSION en Crostini
echo Se distribuye con la esperanza de que sea util, pero sin ninguna garantia
echo ***No repetir la ejecucion de las etapas***
sleep 3s
#
PS3='Elige la etapa de configuracion: '
options=("Configurar usuario y locale" "Instalar software" "Salir")
select opt in "${options[@]}"
do
	case $opt in
	"Configurar usuario y locale")
		#
		sudo apt update && sudo apt full-upgrade && sudo apt install curl wget nano git dialog gpg gh -y
		env | grep LANG
		export LANG=es_ES.UTF-8
		dpkg-reconfigure locales
		#
		#Instalar utilidades de APT
		sudo apt install apt-listbugs apt-listchanges apt-utils apt-transport-https -y
		#
		#Cambiar repositorios de Debian
		echo Respaldando sources.list
		sudo cp /etc/apt/sources.list /etc/apt/sources-default.list.bak
		Setup-Debian-Repos
		#
		#Modificar grupos
		sudo groupadd lp
		sudo groupadd optical
		sudo groupadd power
		sudo groupadd storage
		sudo groupadd wheel
		sudo usermod -aG lp gerardohd
		sudo usermod -aG optical gerardohd
		sudo usermod -aG power gerardohd
		sudo usermod -aG storage gerardohd
		sudo usermod -aG wheel gerardohd
		#
		#Soporte de Flatpak
		sudo apt install flatpak xdg-desktop-portal-xapp flatpak-xdg-utils -y
		sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
		sudo flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo
		sudo flatpak remote-add --if-not-exists appcenter https://flatpak.elementary.io/repo.flatpakrepo
		#flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
		sudo flatpak update --appstream
		#
		#Soporte de Snap
		sudo apt install snapd apparmor-utils apparmor-profiles* -y
		sudo snap install snapd
		sudo snap login
		#
		#Soporte de sudo sin contraseña usando WSL-Hello-sudo
		mkdir Git
		cd Git
		wget http://github.com/nullpo-head/WSL-Hello-sudo/releases/latest/download/release.tar.gz
		#wget https://github.com/lzlrd/wsl-hello-sudo/releases/latest/download/release.tar.gz
		tar xvf release.tar.gz
		cd release
		./install.sh
		cd ..
		rm -rf release* && ls
		cd ~
		#
		sudo poweroff
	break
	;;
	"Instalar software")
		#Actualizar carpetas de usuario
		xdg-user-dirs-update --force
		#
		#Utilidades de sistema
		sudo apt install bash-completion man-db manpages-es dialog pkexec-y
		sudo apt install cmatrix cmatrix-xfont fastfetch -y
		sudo apt install cmake dos2unix -y
		sudo apt install btrfs-progs f2fs-tools reiserfsprogs xfsprogs ntfs-3g jfsutils xfsdump nilfs-tools psmisc -y
		#sudo apt install gvfs* fuse fuse-overlayfs fuse2fs exfat-fuse fusefat fuseiso* -y #desactivado porque hay conflicto de fuse con fuse3
		sudo apt install lzip minizip unace arj ncompress p7zip-full unrar-free lrzip zip squashfs-tools lzop rzip xz-utils -y
		sudo apt install pv tar cgpt vboot-utils -y
		#sudo apt install ffmpegthumbnailer -y
		sudo apt install sbsigntool -y
		sudo apt install adb fastboot -y
		sudo apt install openssh-server sshfs -y
		sudo apt install exiv2 -y
		#
		#Motores de temas
		#sudo apt install gtk2-engines* -y
		#sudo apt install qt5-style-kvantum* -y
		#
		#Compiladores y utilidades
		#sudo apt install binutils acl attr -y
		#sudo apt install clang clang-tools -y
		#sudo apt install cpp -y
		#sudo apt install gcc -y
		#sudo apt install gcc-avr -y
		#sudo apt install gcc-bpf -y
		#sudo apt install gcc-snapshot -y
		#sudo apt install gccgo -y
		#sudo apt install gdc -y
		#sudo apt install gfortran -y
		#sudo apt install gobjc -y
		#sudo apt install gobjc++ -y
		#sudo apt install golang-any
		#sudo apt install libc++1 -y
		#sudo apt install mcpp -y
		#sudo apt install tcc -y
		#sudo apt install cmake cmake-extras -y
		#sudo apt install php -y
		#sudo apt install python3-pip -y
		#sudo apt install javascript-common -y
		#sudo apt install markdown -y
		#
		echo  -=Software Grafico=-
		#sudo apt install gparted -y
		sudo apt install gnome-software gnome-software-plugin* apt-config-icons-hidpi -y
		#sudo apt install gdisk -y
		#sudo apt install nautilus -y
		Setup-Flatpaks
		#
		echo  -=Actualizando y limpiando $NAME $VERSION=-
		sudo apt update
		sudo apt upgrade -y
		sudo apt clean
		sudo apt autoclean
		sudo apt autoremove -y
		df -h
		sleep 3s
		fastfetch
		#
	break
	;;
	"Salir")
	break
	;;
	*) echo invalid option;;
	esac
done
#
