#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD
echo Script creado para configurar un sistema $NAME en WSL
echo Se distribuye con la esperanza de que sea util, pero sin ninguna garantia
sleep 3s
#
sudo apt install bash-completion manpages-es dialog -y
sudo apt install apt-listbugs apt-listchanges apt-utils apt-transport-https -y
sudo apt install cmatrix cmatrix-xfont fastfetch -y
#
#Cambiar repositorios de Debian
Setup-Debian-Repos
#
sudo apt install curl gpg wget git -y
sudo apt install cmake -y
sudo apt install btrfs-progs f2fs-tools reiserfsprogs xfsprogs ntfs-3g jfsutils xfsdump nilfs-tools -y
#sudo apt install gvfs* fuse fuse-overlayfs fuse-zip fuse2fs exfat-fuse fusefat fuseiso* -y #desactivado porque hay conflicto de fuse con fuse3
sudo apt install lzip minizip unace arj ncompress p7zip-full unrar-free lrzip zip squashfs-tools lzop rzip -y
sudo apt install pv tar cgpt vboot-utils -y
sudo apt install apt-config-icons-hidpi -y
sudo apt install sbsigntool -y
sudo apt install adb fastboot -y
sudo apt install openssh-server sshfs -y
sudo apt install ffmpegthumbnailer exiv2 -y
#
#Soporte Flatpak
#sudo apt install flatpak xdg-desktop-portal-xapp -y
#sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
#sudo flatpak update --appstream
#
#Motores de temas
sudo apt install gtk2-engines -y
sudo apt install gtk2-engines-aurora -y
sudo apt install gtk2-engines-murrine -y
sudo apt install gtk2-engines-oxygen -y
sudo apt install qt5-style-kvantum*
#
Setup-Tweaks
#
#Compiladores y utilidades
#sudo apt install binutils acl attr
#sudo apt install clang clang-tools
#sudo apt install cpp -y
#sudo apt install gcc -y
#sudo apt install gcc-avr
#sudo apt install gcc-bpf
#sudo apt install gcc-opt -y
#sudo apt install gcc-snapshot
#sudo apt install gccgo
#sudo apt install gccgo-go
#sudo apt install gdc
#sudo apt install gfortran
#sudo apt install gobjc -y
#sudo apt install gobjc++ -y
#sudo apt install golang-any
#sudo apt install golang-go
#sudo apt install libc++1 -y
#sudo apt install mcpp -y
#sudo apt install tcc -y
#sudo apt install cmake cmake-extras -y
#sudo apt install php -y
#sudo apt install python-pip -y 
#sudo apt install javascript-common -y
#sudo apt install markdown -y
#
#echo  -=Software Grafico=-
#sudo apt install gparted -y
#sudo apt install gnome-software gnome-software-plugin* -y
#sudo apt install gdisk -y
#Setup-Flatpaks
#gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3' && gsettings set org.gnome.desktop.interface color-scheme 'default'
#
echo  -=Actualizando y limpiando $NAME $VERSION=-
sudo apt update
sudo apt upgrade -y
sudo apt clean
sudo apt autoclean
sudo apt autoremove -y
df -h
sleep 3s
fastfetch
#