#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD
echo Script creado para configurar $NAME $VERSION en Crostini
echo Se distribuye con la esperanza de que sea util, pero sin ninguna garantia
echo ***No repetir la ejecucion de las etapas***
sleep 3s
#
PS3='Elige la etapa de configuracion: '
options=("Configurar usuario y locale" "Instalar software" "Salir")
select opt in "${options[@]}"
do
    case $opt in
	"Configurar usuario y locale")
	  echo Introduzca clave de su usuario
	  sudo addgroup lp
	  sudo addgroup optical
	  sudo addgroup power
	  sudo addgroup storage
	  sudo addgroup wheel
	  sudo usermod -aG optical,power,storage,wheel gerardohd
	  sudo nano /etc/sudoers
	  #
	  sudo sed -i 's/LANG=en_US.UTF-8/LANG=es_MX.UTF-8/g' /etc/default/locale
	  sudo sed -i 's/en_US.UTF-8/#en_US.UTF-8/g' /etc/locale.gen
	  sudo sed -i 's/# es_MX.UTF-8/es_MX.UTF-8/g' /etc/locale.gen
	  sudo locale-gen
	  #
	  sudo apt install bash-completion manpages-es dialog -y #preinstalado en C330
	  sudo apt install apt-listbugs apt-listchanges apt-utils apt-transport-https -y
	  sudo apt install cmatrix cmatrix-xfont fastfetch -y
	  sudo apt install curl gpg wget git -y
	  #
	  sudo poweroff
	  break
	  ;;
	"Instalar software")
	  #
	  #sudo apt-mark hold cros-guest-tools
	  #sudo apt-mark hold cros-im
	  #Cambiar repositorios de Debian
	  echo Respaldando sources.list
	  sudo cp /etc/apt/sources.list /etc/apt/sources-default.list.bak
	  Setup-Debian-Repos
	  #
	  sudo apt install btrfs-progs f2fs-tools reiserfsprogs xfsprogs ntfs-3g jfsutils xfsdump nilfs-tools -y
	  sudo apt install lzip minizip unace arj ncompress p7zip-full unrar-free lrzip zip squashfs-tools lzop rzip xz-utils -y
	  sudo apt install pv tar cgpt vboot-utils -y
	  sudo apt install sbsigntool -y
	  sudo apt install adb fastboot -y
	  sudo apt install ffmpegthumbnailer exiv2 -y
	  #sudo apt install youtube-dl -y
	  sudo apt install binutils acl attr -y
	  #Fuentes
	  sudo apt install fonts-cantarell fonts-liberation fonts-linuxlibertine -y
	  sudo apt install fonts-crosextra* -y
	  sudo apt install ttf-mscorefonts-installer cabextract fonts-ibm-plex -y
	  mkdir .fonts
	  wget -qO- http://plasmasturm.org/code/vistafonts-installer/vistafonts-installer | bash
	  rm PowerPointViewer.exe
	  #
	  sudo apt clean
	  sudo apt autoclean
	  #
	  #Soporte Flatpak
	  sudo apt install flatpak xdg-desktop-portal-xapp -y
	  sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
	  sudo flatpak update --appstream
	  #echo Descargando flathub.flatpakrepo
	  #echo Si no se instala el archivo mediante gnome-software, este no mostrara los flatpak
	  #sleep 5s
	  #wget -c https://dl.flathub.org/repo/flathub.flatpakrepo
	  #
	  #Motores de temas
	  sudo apt install gtk2-engines -y
	  sudo apt install gtk2-engines-aurora -y
	  sudo apt install gtk2-engines-murrine -y
	  sudo apt install gtk2-engines-oxygen -y
	  sudo apt install qt5-style-kvantum*
	  #
	  Setup-Tweaks
	  #
	  gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3' && gsettings set org.gnome.desktop.interface color-scheme 'default'
	  #
	  echo Cambiando tema a Adwaita y fuente a Cantarell
	  sudo sed -i 's/CrosAdapta/adw-gtk3/g' /etc/gtk-2.0/gtkrc
	  sudo sed -i 's/CrosAdapta/adw-gtk3/g' /etc/gtk-3.0/settings.ini
	  sudo sed -i 's/Roboto 10/Cantarell 11/g' /etc/gtk-2.0/gtkrc
	  sudo sed -i 's/Roboto 10/Cantarell 11/g' /etc/gtk-3.0/settings.ini
	  #
	  #echo Iniciando propiedades de software, activar repositorios y actualizaciones de seguridad
	  #sleep 3s
	  #xhost +
	  #sudo software-properties-gtk
	  #
	  echo Actualizando software
	  sudo apt update
	  sudo apt dist-upgrade -y
	  sudo apt autoremove -y
	  #
	  echo  -=Software Grafico=-
	  cmd=(dialog --separate-output --checklist "Elige el software a instalar: " 22 76 16)
	  options=(1 "Software desde APT" on
	           2 "LibreOffice y GIMP" off
	           3 "Visual Studio Code" on
	           4 "Flatpaks" on)
	  choices=$("${cmd[@]}" "${options[@]}" 2>&1 >/dev/tty)
	  clear
	  for choice in $choices
	  do
	      case $choice in
	  	1)
          sudo apt install gimp gimp-data-extras inkscape inkscape-open-symbols inkscape-tutorials -y
		  sudo apt install baobab -y
		  sudo apt install gnome-software gnome-software-plugin* -y
          sudo apt install gdisk -y
          sudo apt install sshfs -y
		  sudo apt install thunar thunar-archive-plugin xarchiver xfce4-settings -y
	  	  ;;
	  	2)
          sudo apt install libreoffice-gtk3 liblibreofficekitgtk libreoffice-voikko mythes-es -y
		  sudo apt install hunspell-es hyphen-es libreoffice-gtk4 libreoffice-help-es libreoffice-l10n-es -y
          sudo apt install libreoffice-style-breeze libreoffice-style-sifr libreoffice-style-sukapura -y
	  	  sudo apt install libreoffice-l10n-es -y
	  	  sudo apt install libreoffice-java-common -y
	  	  sudo apt install libreoffice-calc -y
	  	  sudo apt install libreoffice-impress -y
	  	  sudo apt install libreoffice-writer -y
		  #
	  	  #sudo apt install cups system-config-printer -y
	  	  #sudo apt install printer-driver-cups-pdf -y
	  	  #sudo apt install printer-driver-escpr psutils -y
	  	  #
	  	  #echo Iniciando configuracion de impresora
	  	  #sudo system-config-printer
	  	  #
		  sudo apt install gimp gimp-data-extras -y
	  	  ;;
	  	3)
	  	  sudo apt-get install wget gpg
	  	  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
		  sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
		  sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
		  rm -f packages.microsoft.gpg
		  sudo apt update
		  sudo apt install code -y
	  	  ;;
	  	4)
	  	  Setup-Flatpaks
	  	  ;;
	     esac
	  done
	  #
	  echo -=Aplicando modificaciones a gsettings=-
	  sleep 2s
	  echo Reconfigurando Cantarell como tipografia en GNOME Shell
	  gsettings set org.gnome.desktop.interface font-name 'Cantarell 11'
	  gsettings set org.gnome.desktop.interface document-font-name 'Cantarell 11'
	  gsettings set org.gnome.desktop.interface monospace-font-name 'Noto Sans Mono Regular 12'
	  gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Cantarell Bold 11'
	  echo Configurando botones de la barra de titulo
	  gsettings set org.gnome.desktop.wm.preferences button-layout ':close'
	  echo Configurando Tema GTK
	  gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3'
	  #echo Activando CSD en GNOME Terminal
	  #gsettings set org.gnome.Terminal.Legacy.Settings headerbar 'true'
	  #
	  echo Actualizando carpetas de usuario
	  xdg-user-dirs-update
	  #
	  echo  -=Actualizando y limpiando $NAME $VERSION=-
	  sudo apt update
	  sudo apt upgrade -y
	  sudo apt autoremove -y
	  sudo apt clean
	  sudo apt autoclean
	  break
	  ;;
	"Salir")
	  break
	  ;;
	*) echo invalid option;;
	esac
done
#
