#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD
echo Script creado para configurar $NAME $VERSION en Crostini
echo Se distribuye con la esperanza de que sea util, pero sin ninguna garantia
#
sudo apt install apt-utils pv tar cgpt
sudo apt install binutils acl attr
#
sudo apt install bash-completion manpages-es
#
sudo apt install btrfs-progs f2fs-tools reiserfsprogs xfsprogs ntfs-3g jfsutils xfsdump nilfs-tools
sudo apt install lzip minizip unace arj ncompress p7zip unrar-free lrzip zip squashfs-tools lzop rzip
sudo apt install adb fastboot
#
sudo apt clean
sudo apt autoclean
#
