#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD
echo Script creado para configurar $NAME $VERSION en Crostini
echo Se distribuye con la esperanza de que sea util, pero sin ninguna garantia
#
sudo apt install apt-utils pv tar cgpt
sudo apt install binutils acl attr
#
sudo apt install bash-completion manpages-es
#
sudo apt install btrfs-progs f2fs-tools reiserfsprogs xfsprogs ntfs-3g jfsutils xfsdump nilfs-tools
sudo apt install lzip minizip unace arj ncompress p7zip unrar-free lrzip zip squashfs-tools lzop rzip
sudo apt install adb fastboot
#
sudo apt clean
sudo apt autoclean
#
#sudo apt install clang clang-tools
sudo apt install cpp -y
sudo apt install gcc -y
#sudo apt install gcc-avr
#sudo apt install gcc-bpf
sudo apt install gcc-opt -y
#sudo apt install gcc-snapshot
#sudo apt install gccgo
#sudo apt install gccgo-go
#sudo apt install gdc
#sudo apt install gfortran
sudo apt install gobjc -y
sudo apt install gobjc++ -y
#sudo apt install golang-any
#sudo apt install golang-go
sudo apt install libc++1 -y
sudo apt install mcpp -y
sudo apt install tcc -y
sudo apt install cmake cmake-extras -y
sudo apt install php -y
sudo apt install python-pip -y 
sudo apt install javascript-common -y
sudo apt install markdown -y

#cargo rust-all