#!/bin/bash
source /etc/os-release
#
echo	------==Script Creado por GerardoHD==------
echo https://www.github.com/GerardoHD/Linux
echo Script creado para configurar un sistema $NAME 20.04
echo Se distribuye con la esperanza de que sea útil, pero sin ninguna garantía
sleep 3s
#
	sudo apt install ubuntu-restricted-extras -y
	sudo apt install chrome-gnome-shell -y
	sudo apt install flatpak sshfs -y
	sudo apt install dconf-tools git curl -y
	sudo apt install android-tools-adb android-tools-fastboot -y
	sudo apt install autoconf automake cmake -y
	sudo apt install gparted -y
#
	sudo apt install synaptic -y
	sudo apt install gnome-contacts nautilus-admin -y
#
	sudo apt install geary calibre menulibre -y
#
echo  -=Descargando Google Chrome=-
wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb
#
	#sudo apt purge libreoffice*
	#sudo apt remove gnome-mahjongg
	#sudo apt purge remmina aisleriot gnome-todo
#
	echo Descargando reglas de polkit para administrar sistema sin autenticarse
	sudo sudo mkdir /etc/polkit-1/rules.d/
	sudo wget -c https://raw.githubusercontent.com/GerardoHD/Scripts/main/FFLD/10-rules.rules -O /etc/polkit-1/rules.d/10-rules.rules
#
echo  -=Actualizando y limpiando $NAME $VERSION=-
sudo apt update
sudo apt upgrade -y
sudo apt clean
sudo apt autoclean
sudo apt autoremove -y
df -h
sleep 3s
#
